// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtPklowGQG-mkG9ISfRiektvDokbODYyw',
    appId: '1:530303644832:web:c882bbe42798c8d6d905c5',
    messagingSenderId: '530303644832',
    projectId: 'women-s-health-tracker',
    authDomain: 'women-s-health-tracker.firebaseapp.com',
    storageBucket: 'women-s-health-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxHL8Dqzu9Oh6t024iShdD8I3TT1tivmU',
    appId: '1:530303644832:android:0af98d56f00bcf79d905c5',
    messagingSenderId: '530303644832',
    projectId: 'women-s-health-tracker',
    storageBucket: 'women-s-health-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2yge81GXKyubuRNKS20D2qPQo67O46OY',
    appId: '1:530303644832:ios:ce60f667be11aafbd905c5',
    messagingSenderId: '530303644832',
    projectId: 'women-s-health-tracker',
    storageBucket: 'women-s-health-tracker.firebasestorage.app',
    iosBundleId: 'com.example.womenHealthTracker',
  );
}
